### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by OnGitHubSchatz** [BCLibCoop/nnels-pipeline-gadget#1]
Related to #144 

## Background

- We receive MARC record sets (both raw and MARCXML) and accessible book files from publishers.
- Within an individual MARC record is a field entry (035) identifying a system control number (SCN).
- Received files usually follow the scheme: SCN_title.format, e.g. `208855_A_Riveting_Tale.zip` See Move or append SCN below

Other formats apply where deflation compression isn't appropriate.

## Problems

1. Sometimes the SCN is only in the 035 for the record and not present in corresponding filename.
2. Sometimes the filename consists only of SCN and no title but the records contain both.
3. Sometimes no SCN exists or an unsuitable one was used, so we need to generate and re-insert.

### SCN and Two-column Generation

- [x] Generate new SCNs from timestamps in a 'basic format' of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) or [Canada's TBITS 36](http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=17284) for each title in a sorted list of titles. In the past we used `YYYYMMDDHHMMSS` however we need to include milliseconds and microseconds if generating from a script to avoid collisions.

- [x] Generate 2-column Tab-separated values file of SCNs and titles from a given set of records. MARCXML is preferred because it can be parsed with XPath.

### Title Conversion

- [x] Given a camel-cased title, e.g. _Where the Wild Things Are_ and/or a title with punctuation e.g. _Fish in a Tree: A novel_ lowercase all subsequent letters, remove punctuation ` , : . ' ? & `and replace spaces with underscores except just before the file format.

### Move or append SCN

- [x] Given a filename pattern, for each filename, get its title, look-up its corresponding SCN from the two-column file and append it to the end of the filename.
- [x] Given a filename beginning with a SCN, cut and append it to end of filename for human legibility in file systems and sorting by title.

Technical Requirements

- [x] This should take the form of a command-line script with passed options for each mode.

> Needs to run remotely and not on local machines due to the requirement of temporarily staging content files from S3 and staying on the LAN.

- [x] Run recursively on a group of files within specified folder, down to 2 levels of hierarchy.
- [x] Should require minimal dependencies available for an Ubuntu Server LTS box. We support Ruby, Python, PHP, Perl. Bash script is also OK to lean on. 
- [x] A dry-run mode for each operation is essential.

I'm available to collaborate on this project and had started planning some of it in the [Click framework](http://click.pocoo.org/5/) (Python) for command-line apps, which I **highly** recommend.

**Comment by flittle8** [comment]
@gitschatz This looks good to me. 
Just one minor thing - you mentioned our usual filenaming scheme is SCN_title.format, but it is actually Title_SRN.format. We changed this for accessibility purposes.

**Comment by OnGitHubSchatz** [comment]
@flittle8 Ah let me correct that part - I meant to describe the scheme we usually receive files in.

**Comment by AlanBridgeman** [comment]
I've put up some initial documentation on what I've done so far and what I've been working on but this definitely clarifies a lot of things that I'll need to work on and specifically some of the naming convention stuff which I think I'd identified as an issue but you've provided proper information for. I had written this initially in BASH thinking it was a straightforward renaming script but now I'm thinking more towards Python as you suggested. It'll just take a bit because I haven't done XML parsing in Python before so I'll have to figure out the libraries but I assume its fairly straightforward as it should be pretty similar to other languages which I've worked with before.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Cool, will be reviewing your docs shortly.

**Comment by AlanBridgeman** [comment]
Updated the checklist with what has been finished more or less there is still some work on this part to be done but I'm hoping over the next couple of hours and early tomorrow this will get done.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Thanks, will take a look tomorrow.
No rush on this, we have a timeline of a few weeks at least to refine and test.

**Comment by AlanBridgeman** [comment]
Have introduced a CLI component to the scripts but still need to work to get them to work with automation
