### ISSUE TITLE
Case Sensitivity and "Cleaning" of Name Comparison

### ISSUE THREAD

**Issue by AlanBridgeman** [BCLibCoop/nnels-pipeline-gadget#4]
One challenge I've now come across is this issue that I need to recognize and query based on the name which for the most part is going well but looking over the most recent results I was quite confused why so many of the files weren't being recognized as containing the name. After some digging I found out that the problem is the dictionary file I'm using has the entry in it but it has a different case for some of the letters. Consequently I need to investigate if the string comparisons need to be done case sensitively or can be done case insensitively. 

To add to this I also noticed that there were a few entries with say an extraneous underscore or other character at the end so I wonder if I should "clean" this and remove this or keep it. 

These are mostly practice type questions but the problem of course is each one will introduce some complexity in one way or another so need to make sure I'm headed in the right direction

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Ah yes, titles have initial letter capitalized in MARC 245 $a but are often camel-case in the filename. Whichever is easiest to implement - possibly initial case. Though I can see why you'd want the comparison to be case insensitive.

Regarding the extraneous special chars in titles - I noticed that too - that's what my pull request should be addressing.
