### ISSUE TITLE
Different find command flags

### ISSUE THREAD

**Issue by OnGitHubSchatz** [BCLibCoop/nnels-pipeline-gadget#5]
Regarding commit aed0770b93abb:
The find subprocess failed on GNU/Linux because -E is an unknown predicate, being the BSD-flavour. I believe that -regextype posix-extended is equivalent. This also needs shell=True set for some reason.

Do you have any suggestions here for making this more OS-agnostic?

However, I next hit the following:

```
$ python2.7 cli.py -d output.txt -p '[0-9]+_.*'
Opening <type 'file'>
What would you like to do?: rename
Using augmented pattern: .*/[0-9]+_.*
['find', '.', '-regextype posix-extended', '-regex', u'(.*/[0-9]+_.*)']
The filename seems to be unreadable
Traceback (most recent call last):
  File "cli.py", line 34, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 29, in main
    globals()[callbacks[input]](locals()[callbackArgs[input]])
  File "/home/schatz/workspace/nnels-pipeline-gadget/rename_files.py", line 369, in func_rename
    get_name_parts(book)
  File "/home/schatz/workspace/nnels-pipeline-gadget/rename_files.py", line 292, in get_name_parts
    if '_' in filename:
NameError: global name 'filename' is not defined
```
`
$ find . -regextype posix-extended -regex '.*/[0-9]+_.*'` returns files

Am I missing a dependency ?

**Comment by AlanBridgeman** [comment]
@gitschatz Yeah this is definitely an issue. I recently set up a ubuntu server VM that I'll be testing as soon as I finish the current part (I've made some major changes to the storage model throughout the program hoping to post that soon and be on testing later tonight early tomorrow.
You're probably not missing a dependency but minor difference between versions of Bash, find, etc...

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman OK thanks.

While awaiting your changes to storage model and testing, I [branched off](https://github.com/BCLibCoop/nnels-pipeline-gadget/commits/specify-target-dir) to [add a target directory option](https://github.com/BCLibCoop/nnels-pipeline-gadget/commit/6fb04692df1f47ad9214a2eb96631f7b88292466) and [fixed the find subprocess call for Linux](https://github.com/BCLibCoop/nnels-pipeline-gadget/commit/94f90ad023cc13692329ea9ef232fd2c08dc4e7f) (if shell=True it needs to be all one string or they will not be expanded improperly).

Specifying a place for target files to reside is safer and fits my use-case better. Feel free to rework these changes as needed, I definitely took some shortcuts.

**Comment by gitschatz** [comment]
Now that rename executes for me, I notice func_rename doesn't get into the business of renaming the files in the testdata yet:

```
$ python2.7 cli.py -d output.txt -p '[0-9]+_.*' -t 'testdata'
Opening <type 'file'>
What would you like to do?: rename
Using augmented pattern: .*/[0-9]+_.*
find testdata -regextype posix-extended -regex '.*/[0-9]+_.*'
None
Tokens: [u'946062815', u'open', u'modernisms']
Do permutation stuff
Setting the SCN: 946062815
None
Tokens: [u'1001573653', u'DAISY202']
Setting the SCN: 1001573653
Changed book type to <BookFileType.DAISY202_Type object at 0x7fecf5f301d0>
None
Tokens: [u'944246088', u'Good', u'corporation', u'bad', u'corporation']
Do permutation stuff
Setting the SCN: 944246088
Setting the title: Good_corporation_bad_corporation
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/946062815_open_modernisms.zip
| File Name: 946062815_open_modernisms.zip
| Book SCN: 946062815
| Book Title: None
| Book Type: None
|----------------------------------------------------|
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/1001573653_DAISY202.zip
| File Name: 1001573653_DAISY202.zip
| Book SCN: 1001573653
| Book Title: None
| Book Type: <BookFileType.DAISY202_Type object at 0x7fecf5f301d0>
|----------------------------------------------------|
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/944246088_Good_corporation_bad_corporation.zip
| File Name: 944246088_Good_corporation_bad_corporation.zip
| Book SCN: 944246088
| Book Title: Good_corporation_bad_corporation
| Book Type: None
|----------------------------------------------------|
```

These three books are present in my output.txt with both SCN and title, but 946062815_open_modernisms.zip 's Title isn't parsed and 1001573653_DAISY202's Title doesn't get looked up in the dict.

We also seem to not get past [line 388](https://github.com/BCLibCoop/nnels-pipeline-gadget/blob/specify-target-dir/rename_files.py#L388) because Book SCN: is set.

**Comment by AlanBridgeman** [comment]
@gitschatz I also added a target directory option now thought it still isn't fully implemented to the interface as of yet and I accepted your changes to the find command flags. I actually wanted to quickly address your question of doing this OS agnostically in theory we could do it though my fear is it would be far less efficient and cost a lot of overhead particularly looking at the whole file tree beneath the provided directlry as I thin k you mentioned earlier we could do this to a designated level but given I don't see portability of the system as a massively critical aspect and think performance is more critical given this hopefully will scale for large sets of data I feel like using the built in utility may be more effic ient for us. Do you agree?

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Portability is medium priority - is checking OS with https://docs.python.org/2/library/sys.html#sys.platform and creating different args to pass to find a problem?

By built-utility you mean ``find``, right? If so, I agree. In the requirements I mentioned 2 levels of hierarchy from specified target directory and I think that is really the maximum we will encounter in a collection.

Let me know if I missed addressing anything.

**Comment by AlanBridgeman** [comment]
@gitschatz Yeah, that sys call is definitely an option. For the moment I just put in a global variable as it simple and doesn't require any dependencies. I mean if I had more time I probably would do something using the os module and implement it myself it just a lot easier particularly because I wanted to support regex for scalability and reuse reasons.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Cool, that works for me.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Back to testing again and find subprocess on Linux broke again (even with OS = Linux). Two changes needed:

1) Merge in changes from https://github.com/BCLibCoop/nnels-pipeline-gadget/commit/94f90ad023cc13692329ea9ef232fd2c08dc4e7f#diff-676c3535d9b0338d5212c94bc47e782e
Shell=True, join all args by a space and use single-quotes over parentheses on Linux

2) There is another use of find in https://github.com/BCLibCoop/nnels-pipeline-gadget/blob/develop/Metadata_Parsers.py#L875 which requires branching by OS. Should OS and Debug be global vars set in cli.py?

**Comment by OnGitHubSchatz** [comment]
For item 1 - the single quotes for Linux need to happen in [combine_regex function in func.py](https://github.com/BCLibCoop/nnels-pipeline-gadget/blob/develop/funcs.py#L87)

**Comment by AlanBridgeman** [comment]
@gitschatz yeah I've been trying to figure out the best way to have globals across files. The major options are: to pass it as a parameter or we can implement it as a config object. The latter is more scalable but the former is probably a little easier to implement so tradeoffs

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Config object is preferable long term but let's - pass the global as param for now so both Farrah and I can test on our respective systems. Thanks!

**Comment by AlanBridgeman** [comment]
@gitschatz sounds good. i can't foresee any problems that would come from this so I should be able to have this dine easily by first thing tomorrow.

**Comment by OnGitHubSchatz** [comment]
I took a crack at the config on [this branch](https://github.com/BCLibCoop/nnels-pipeline-gadget/tree/posix) to use on a few sets with simple SCNs.
