### ISSUE TITLE
Buggy Rename Functionality

### ISSUE THREAD

**Issue by AlanBridgeman** [BCLibCoop/nnels-pipeline-gadget#7]
After finishing a basic version of the renaming functionality there seems to be some annomellies among the renaming some work fine but others don't will need to continue to work on this to get this corrected.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman I'll take a look after lunch today - can you comment on the bugginess you are seeing a bit more?

**Comment by AlanBridgeman** [comment]
@gitschatz Mostly I'm getting None values for files that I should be able to rename I have been working on it since yesterday so I'll make sure to do another push within the next hour

**Comment by AlanBridgeman** [comment]
@gitschatz So it looks like somehow I'm getting duplicates of entries where one is mapped to None and another is mapped to the proper value will need to investigate further. Also will be pushing (somewhat related wasn't sure if it was part of the problem) code changes soon.

**Comment by AlanBridgeman** [comment]
Figured out the bug was coming from an excess line of code it now works except for one bug which I'll create a seperate issue for.
